-- Generado por scripts/generar-carga-banco.mjs · NO editar a mano.
-- Fuente: ../content/sociales-f1f2-faltantes-2026b.js · clave_origen = modelo

insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('f358f134-b057-44df-99e4-0c30fdac1c92', 'situacion', 'FRAGMENTO', 'ctx-sit', 'Una académica colombiana, a propósito de la participación de las mujeres en la justicia internacional, señala lo siguiente: "En total, solo el 17 % de los miembros de las cortes internacionales son mujeres. De igual forma, 19 de los 52 procedimientos especiales de la ONU no han sido jamás liderados por una mujer; en el Comité de Derechos Humanos de la ONU, solo 5 de sus 18 miembros son mujeres y en el comité de Derechos Económicos, Sociales y Culturales, solo 3 de los 18 miembros son mujeres. Por eso, cuando algunas mujeres sugieren que ya estamos en condiciones de llegar a estos cargos sin que entre a operar la paridad o un régimen de cuotas [normatividad que busca garantizar la presencia de un porcentaje mínimo de personas con ciertas características en una entidad o cargo], están juzgando a partir de su propia condición y no a partir de la estadística. Al menos, en el espacio de la justicia internacional, estamos muy lejos de jugar bajo unas reglas de juego justas". (Tomado de: Borda, S. (2016). La justicia internacional no es negocio de mujeres. Revista Arcadia)');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('8cb91aa4-e84e-4af2-8a91-6d1f5296b0a7', 'situacion', 'FRAGMENTO', 'ctx-sit', '"La Declaración Universal de los Derechos Humanos establece que los seres humanos nacen libres e iguales en dignidad y derechos y que tienen derecho a la vida, la libertad y la seguridad de su persona, a la libertad de expresión, a no ser esclavizados, a un juicio justo y a la igualdad ante la ley. También a la libertad de circulación, a una nacionalidad, a contraer matrimonio y fundar una familia así como a un trabajo y a un salario igualitario". (Tomado y adaptado de: Naciones Unidas, ¿Qué son los derechos humanos?)');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('ae37e03a-5143-4b1a-a247-52b9bc2327f3', 'situacion', 'FRAGMENTO', 'ctx-sit', 'El 10 de diciembre de 1948, la Asamblea General de las Naciones Unidas aprobó y proclamó la Declaración Universal de Derechos Humanos. En el segundo artículo de este documento se estableció que: <br><br>1. Toda persona tiene todos los derechos y libertades proclamados en esta Declaración, sin distinción alguna de raza, color, sexo, idioma, religión, opinión política o de cualquier otra índole, origen nacional o social, posición económica, nacimiento o cualquier otra condición.<br><br>2. Además, no se hará distinción alguna fundada en la condición política, jurídica o internacional del país o territorio de cuya jurisdicción dependa una persona, tanto si se trata de un país independiente, como de un territorio bajo administración fiduciaria, no autónoma o sometido a cualquier otra limitación de soberanía.');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('7f337469-a3b2-4f07-94b3-ced30a675328', 'situacion', 'FRAGMENTO', 'ctx-sit', 'Colombia, como país megadiverso, pluriétnico y multicultural, tiene una alta responsabilidad con la conservación del patrimonio natural e inmaterial. Para abordar esta tarea, es necesario crear un sistema de áreas protegidas o reservas naturales, que incluya ejemplos representativos de cada uno de los ecosistemas del país y ofrezca un manejo efectivo de los recursos naturales disponibles y los grupos humanos que los habitan. (Adaptado de: Departamento Nacional de Planeación, DNP, 2010)<br><br>Siguiendo los lineamientos de la política anterior, un grupo de científicos propone crear un área protegida con el objetivo de evitar el deterioro de un ecosistema vulnerable, producto de la explotación desmedida de los recursos naturales que alberga. La nueva reserva, ubicada en territorios históricamente ocupados por pueblos indígenas, sería administrada exclusivamente por un grupo de profesionales e investigadores y estaría encaminada a la protección de los recursos naturales disponibles y el uso de estos desde una perspectiva sostenible a largo plazo.');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('afe491ee-272c-44de-8c82-9f83249ce845', 'situacion', 'SITUACIÓN', 'ctx-sit', 'En una ciudad hay algunos barrios inundados, producto de las fuertes lluvias; esto ha provocado desplazamientos internos, y cientos de personas han perdido sus casas con todas sus pertenencias. Ante esta situación, los funcionarios de la alcaldía han decidido donar un día de su salario para que, con estos recursos, se apoye a las personas que han sido afectadas por el fenómeno natural.');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('c1dc055a-f204-4f75-ab93-1820a6b717b3', 'situacion', 'SITUACIÓN', 'ctx-sit', 'Diferentes estudios han demostrado que los hijos de padres obesos tienden a elegir alimentos ricos en grasa y a evitar el consumo de frutas y vegetales. Ante este escenario, asesores de algunos organismos internacionales han propuesto que se distribuyan, durante algunos meses, "loncheras saludables" en los hogares. El propósito de la iniciativa es enseñarles a los padres cómo deberían alimentar a sus hijos. El argumento a favor de esta ayuda temporal es que, una vez entrenados, los padres seguirán alimentando a sus hijos de manera saludable.');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('fc3a5615-3bca-4b90-85d5-9b4c4c62145d', 'situacion', 'FRAGMENTO', 'ctx-sit', '"Hasta hace pocos años las estadísticas mostraban que en Estados Unidos aproximadamente un tercio de las adolescentes quedaban embarazadas. Las cifras de una organización reconocida en la materia indicaron que para 2010 el número de embarazadas adolescentes fue menor del 25 %. Y la tendencia ha seguido el mismo curso ya que los datos preliminares de 2013 sugieren una reducción del 22 % con respecto a la tasa de nacimientos desde 2010. De acuerdo con el Instituto Guttmacher, una organización no gubernamental que hace investigaciones sobre salud sexual y reproductiva, la clave está en las exitosas campañas para promover un mayor y mejor uso de anticonceptivos. En contraste con la tendencia a la baja en EE. UU., un informe elaborado por el Fondo de Población de las Naciones Unidas (UNFPA) en 2013 indicó que el embarazo adolescente ha registrado un aumento en América Latina en los últimos años, aunque varios países de la región han invertido presupuesto y los gobiernos se han preocupado por el asunto, en zonas de difícil acceso, lejos de centros urbanos ha sido difícil adelantar las campañas necesarias para combatir el fenómeno. En efecto, cada vez hay más embarazos en adolescentes en la región debido a la pobreza, la desigualdad de género y a la falta de acceso a los servicios en algunas zonas apartadas". (Tomado y adaptado de: BBC Mundo, 2014)');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('533eccc5-9e7b-4da1-9545-d0b093fd0a78', 'situacion', 'FRAGMENTO', 'ctx-sit', 'Octavio no puede moverse. Una enfermedad degenerativa lo mantiene postrado en una silla de ruedas en una villa, un asentamiento urbano informal de los más grandes de Buenos Aires, Argentina. Para Octavio, el barrio es su peor enemigo porque las ambulancias que deben trasladarlo al tratamiento que realiza se niegan a entrar en sus callejuelas. No entran para ayudar a Octavio ni a ningún otro vecino. Dicen que los asaltan, se sienten inseguros. Por eso desde hace dos años funciona la Central de Emergencias Villeras. Cinco vehículos recorren 20 asentamientos de la capital argentina para llegar allí donde el Estado no llega. La Central de Emergencias fue creada por vecinos y vecinas que se cansaron de esperar y estudiaron enfermería y conducción de ambulancias. Hoy atienden los llamados que le llegan desde la villa. La mayor parte de los viajes de estas ambulancias son programados, como el de Octavio, pero también atienden emergencias. Ha sido una cuestión de supervivencia. Los chóferes y las enfermeras viven en la villa y conocen cada metro del laberinto de calles donde trabajan. El sistema de emergencias se sostiene gracias a 500 personas, que trabajan cada día con una lógica que busca cambiar la política del reclamo por la de la acción, no recibe ayuda de sectores privados ni del Estado, y se financia con fiestas, rifas y otros proyectos que permiten comprar medicamentos y equipos. (Tomado y adaptado de: Molina, F. (2017). Las ambulancias villeras salvan vidas en Argentina. El País)');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('2adb8b95-1f5a-4e88-b5bb-2e481ab31155', 'situacion', 'FRAGMENTO', 'ctx-sit', 'El siguiente fragmento pertenece a un discurso de un líder político del siglo XX: "(...) nada queda de la legalidad pretendida; los extranjeros mandan los ejércitos, la anarquía reina en sus campos y ciudades, ninguna de las leyes fundamentales de la nación está en vigor: no se respeta ni la religión, ni la familia, ni la propiedad, y las organizaciones anarquistas y marxistas asaltan, roban, matan muchas veces con la complicidad del Gobierno (...) el bolchevismo seca la hierba (...) Pero nosotros sabremos reedificarlo todo".');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('41828da6-1fd1-4205-b65c-169af2f1e6b3', 'situacion', 'FRAGMENTO', 'ctx-sit', '"Yo tengo el sueño de que todos los hijos de Dios, blancos y negros, judíos o gentiles, católicos o protestantes, serán capaces de unir sus manos y cantar, con las palabras del viejo <em>espiritual</em> negro, ¡Al fin, libres! Gracias, Dios Todopoderoso, al fin somos libres".');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('10f4fce5-b643-4db0-a715-2ee4cd54f0b5', 'situacion', 'FRAGMENTO', 'ctx-sit', '"Ir a la universidad fue una senda abierta a un mundo por explorar, a unas relaciones nuevas por construir y a un autorreconocimiento de potencialidades y capacidades frente a los hombres. La alternativa del control natal replantea a las mujeres su función biológica y abre las posibilidades a vivir la sexualidad de otra manera, al separar reproducción y placer. Desempeñarse laboralmente fuera del hogar, además de reconocimiento social, procura los recursos económicos para aportar como proveedora al hogar, una función reservada para el padre como autoridad. Es el descubrimiento de la autonomía como resultado de la convergencia de todos los cambios, lo que hace que las mujeres se atrevan a aceptar el desafío de unas nuevas condiciones [...]". (Tomado de: Lamus Canavate, Doris. En: La manzana de la discordia, Universidad del Valle)');
insert into public.contextos (id, tipo, etiqueta, clase, contenido) values ('ddadfef6-c2bc-47b6-8944-f7be96f70f23', 'situacion', 'FRAGMENTO', 'ctx-sit', 'Lea con atención los siguientes fragmentos de discursos, sobre la relación Estado-medios de comunicación, pronunciados por un político en 1998 y en 2006, respectivamente:<br><br><strong>Fragmento 1:</strong> "No nacionalizaría ningún medio de comunicación. Basta con los medios que ya tiene el Estado. Hay que repotenciar esos canales y ponerlos a trabajar en función de la educación nacional, de los valores nacionales. Tengo las mejores relaciones con los canales y los medios de comunicación. Los canales deben seguir siendo privados; es más, estamos interesados en que se amplíen y se profundicen" (1998).<br><br><strong>Fragmento 2:</strong> "Ese canal de televisión [privado], se acaba. Se acaba la concesión cedida por el Gobierno. Ya está redactada la medida, así que vayan preparándose, apagando los equipos. No se va a tolerar aquí ningún medio de comunicación que esté al servicio del golpismo, contra el pueblo, contra la nación, contra la independencia nacional, contra la dignidad de la República" (2006).<br><br>El primer fragmento corresponde a una entrevista que el político concedió en 1998 a un medio de comunicación internacional cuando era candidato a la presidencia. El político asumió la presidencia en 1999, enfrentó un fallido golpe de Estado en su contra en 2002, y se mantuvo como presidente hasta su muerte en 2013. El segundo fragmento, por tanto, hace parte de un discurso pronunciado en plaza pública en el 2006, cuando estaba en la mitad de su mandato presidencial.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select 'e823bbc9-dad1-4703-aec1-d8304aa987e6', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'constitucion-y-derechos'),
  (select id from public.lotes where codigo = '2026-B'),
  null, 'Constitución y derechos',
  '¿En cuál de las siguientes situaciones se respetan los derechos del medio ambiente?',
  array['Debido al deterioro del agua en un país, un presidente decide ponerles como requisito a las empresas petroleras del lugar el uso de tecnologías limpias en los procedimientos que realizan.', 'Debido al incremento de la población en una ciudad, un alcalde decide construir nuevas viviendas en los predios cercanos a algunos de los humedales protegidos de la zona.', 'Debido al déficit energético de un país, un presidente decide saltarse varios protocolos de seguridad ambiental con tal de que las plantas nucleares produzcan más energía.', 'Debido al aumento de la población en un municipio, el alcalde decide construir grandes y amplias vías sobre algunos lugares emblemáticos por su fauna y flora.'],
  'Lee cada opción preguntándote qué se sacrifica. Si lo que cede es el ambiente, esa no puede ser la respuesta.', 'publicada', 'modelo', '8393cde32be9661dd9b50258e8f66261';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('e823bbc9-dad1-4703-aec1-d8304aa987e6', 0, 'Exigirle a las petroleras tecnologías limpias es poner el cuidado del agua por encima de la conveniencia de la industria: ahí el derecho al ambiente sano se protege. En las otras tres, el ambiente es justamente lo que se sacrifica — humedales, protocolos de seguridad y hábitats de fauna y flora.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select 'faa427e8-f059-415f-8e0f-7fd348624cc5', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'constitucion-y-derechos'),
  (select id from public.lotes where codigo = '2026-B'),
  'f358f134-b057-44df-99e4-0c30fdac1c92', 'Constitución y derechos',
  'El análisis presentado por la académica se fundamenta en el concepto de',
  array['comunidad internacional.', 'meritocracia laboral.', 'equidad de género.', 'desigualdad social.'],
  'Fíjate en qué variable usa el autor para comparar. Si todas las cifras separan hombres de mujeres, el concepto es de género.', 'publicada', 'modelo', '8fe65ad3786c8456ed862dc9103607e3';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('faa427e8-f059-415f-8e0f-7fd348624cc5', 2, 'Todas las cifras que cita comparan la presencia de mujeres frente a la de hombres en los mismos cargos, y su conclusión es que las reglas de juego no son justas entre unas y otros. Ese desequilibrio entre géneros es lo que nombra la equidad de género. La desigualdad social es más amplia y no explica por qué mide solo por sexo.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select '0212c4ba-88ef-4d3d-9b2b-84b0a0c293f8', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'constitucion-y-derechos'),
  (select id from public.lotes where codigo = '2026-B'),
  '8cb91aa4-e84e-4af2-8a91-6d1f5296b0a7', 'Constitución y derechos',
  'De acuerdo con el fragmento anterior, ¿cuál de las siguientes acciones NO está directamente relacionada con la aplicación de los Derechos Humanos?',
  array['Eliminar las condiciones que causan la discriminación racial o que contribuyen a perpetuarla.', 'Defender la igualdad de oportunidades laborales para mujeres y hombres.', 'Procurar condiciones de vida digna en los establecimientos carcelarios.', 'Promover normas de comportamiento que garanticen la convivencia ciudadana.'],
  'En este tipo de pregunta, empareja cada opción con un derecho del texto. La que se quede sin pareja es la respuesta.', 'publicada', 'modelo', 'f10502e02670120fc591d646f5e1d7f6';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('0212c4ba-88ef-4d3d-9b2b-84b0a0c293f8', 3, 'Las otras tres se conectan con derechos que el fragmento nombra: la igualdad ante la ley, el trabajo con salario igualitario y la dignidad de la persona incluso privada de la libertad. Las normas de convivencia son reglas de trato social que un Estado puede promover, pero no aparecen en la lista como un derecho de la persona.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select 'f80a3d69-0e27-43f5-8a97-412658c3988c', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'constitucion-y-derechos'),
  (select id from public.lotes where codigo = '2026-B'),
  'ae37e03a-5143-4b1a-a247-52b9bc2327f3', 'Constitución y derechos',
  '¿Cuál de los siguientes es un supuesto que se deriva de este segundo artículo de la Declaración de los Derechos Humanos?',
  array['Los Derechos Humanos son aplicables solo si no van en contra de la soberanía del país o territorio al que pertenece una persona.', 'Los Derechos Humanos son aplicables a todas las personas que hayan declarado oficialmente que están de acuerdo con ellos.', 'Los Derechos Humanos se aplican siempre y cuando no vayan en contra de las leyes del país o territorio al que pertenezca la persona.', 'Los Derechos Humanos son aplicables a todos los individuos independientemente de sus características socioculturales.'],
  'Cuando un artículo lista condiciones prohibidas de distinción, lo que afirma es universalidad: aplica a todos sin excepción.', 'publicada', 'modelo', '206ab4a14bf792534f82fe7725cb6a00';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('f80a3d69-0e27-43f5-8a97-412658c3988c', 3, 'El artículo enumera todo aquello que NO puede servir para excluir a alguien: raza, sexo, idioma, religión, opinión, origen, posición económica. Es decir, los derechos valen para cualquiera sin importar de dónde venga ni cómo viva. Las opciones que los condicionan a la soberanía, a las leyes locales o a una aceptación previa dicen justo lo contrario.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select '94cd26b3-ee9b-4f57-9a48-7e535ff97979', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'constitucion-y-derechos'),
  (select id from public.lotes where codigo = '2026-B'),
  '7f337469-a3b2-4f07-94b3-ced30a675328', 'Constitución y derechos',
  'De acuerdo con la información presentada anteriormente, ¿cuál de los siguientes aspectos NO es tenido en cuenta por el grupo de científicos al formular su propuesta de conservación?',
  array['El deber constitucional de los ciudadanos de proteger las riquezas naturales de la nación.', 'El derecho de las comunidades indígenas a participar en las decisiones que afectan el manejo de sus territorios.', 'La formación académica y experticia de las personas encargadas de administrar la reserva.', 'El impacto que pueda tener la academia en el cuidado de los recursos naturales del país.'],
  'La palabra «exclusivamente» casi siempre señala a quién se está excluyendo. Pregúntate quién más debería estar y no está.', 'publicada', 'modelo', 'e97d7b7f326f9e62543efc34d87dd13c';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('94cd26b3-ee9b-4f57-9a48-7e535ff97979', 1, 'La reserva se ubica en territorios ocupados históricamente por pueblos indígenas, pero la propuesta dice que la administrarían «exclusivamente» profesionales e investigadores. Esa palabra deja a las comunidades por fuera de las decisiones sobre su propio territorio. Los otros tres aspectos sí están contemplados: proteger las riquezas naturales, la experticia de quienes administran y el papel de la academia.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select '085d457d-48f9-4c21-8bc0-ca8e46e2d3ea', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'constitucion-y-derechos'),
  (select id from public.lotes where codigo = '2026-B'),
  'afe491ee-272c-44de-8c82-9f83249ce845', 'Constitución y derechos',
  'De acuerdo con la Constitución Política de Colombia, ¿en cuál deber ciudadano se ubica la acción de los funcionarios de la alcaldía?',
  array['Respetar los derechos ajenos y no abusar de los propios.', 'Obrar conforme al principio de solidaridad social.', 'Propender por el mantenimiento de la paz en las comunidades.', 'Participar en la vida política, cívica y comunitaria del país.'],
  'Cuando alguien entrega algo suyo para socorrer a otro ante una calamidad, el deber constitucional en juego es la solidaridad.', 'publicada', 'modelo', '1cdaeaabb1a9e9625c2f3a78447360f1';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('085d457d-48f9-4c21-8bc0-ca8e46e2d3ea', 1, 'Los funcionarios ceden parte de su salario para ayudar a damnificados que no conocen: dar de lo propio para responder ante una calamidad ajena es exactamente el principio de solidaridad social. No están defendiendo un derecho, ni mediando en un conflicto, ni participando en política.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select '9f190c9f-6401-4e92-8836-8afca625ef91', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'economia-y-sociedad'),
  (select id from public.lotes where codigo = '2026-B'),
  'c1dc055a-f204-4f75-ab93-1820a6b717b3', 'Economía y sociedad',
  'Una vez finalice el programa, ¿qué impediría que los padres sigan alimentando a sus hijos de forma saludable?',
  array['Que les sea fácil enseñarles a sus hijos a comer alimentos saludables.', 'Que les sea difícil conseguir los mismos alimentos que estaban en las "loncheras saludables".', 'Que les sea fácil a ellos adoptar buenos hábitos de alimentación.', 'Que les sea difícil encontrar alimentos diferentes a los que estaban en las "loncheras saludables".'],
  'La pregunta busca un obstáculo. Descarta de entrada todo lo que suene a facilidad o a ventaja.', 'publicada', 'modelo', '02d065ff5147f9891ed4afb06ca86f9a';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('9f190c9f-6401-4e92-8836-8afca625ef91', 1, 'El programa entrega los alimentos y enseña a usarlos, pero al terminar los padres tienen que comprarlos ellos mismos. Si no logran conseguir esos alimentos, el aprendizaje no les sirve de nada. Las dos opciones que empiezan con «que les sea fácil» describen facilidades, no obstáculos, y no encontrar alimentos distintos no estorba: los que ya conocen bastan.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select '964ad246-01c2-442e-94ae-ae070bce83b5', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'economia-y-sociedad'),
  (select id from public.lotes where codigo = '2026-B'),
  'fc3a5615-3bca-4b90-85d5-9b4c4c62145d', 'Economía y sociedad',
  'Teniendo en cuenta la anterior información, ¿cuál de los siguientes factores puede explicar la diferencia entre las cifras de embarazo adolescente en Estados Unidos y América Latina?',
  array['La adecuada cobertura en seguridad social en los países de América Latina para todos los estratos.', 'La menor voluntad política de los gobernantes en América Latina, lo cual impide invertir presupuesto para combatir la problemática.', 'La discriminación hacia las mujeres y la violencia de género que prevalecen en Estados Unidos.', 'La mejor comunicación y acceso a zonas apartadas en Estados Unidos, lo cual permite la efectividad de las campañas en ese país.'],
  'Cuando el texto niega explícitamente una explicación, esa opción queda descartada aunque suene razonable.', 'publicada', 'modelo', '0a7876bf5c209b22ca22ef12362b9df9';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('964ad246-01c2-442e-94ae-ae070bce83b5', 3, 'El texto atribuye el éxito estadounidense a unas campañas que funcionaron, y explica que en América Latina esas mismas campañas no llegan a las zonas de difícil acceso. La diferencia está entonces en poder llegar o no con la campaña. El propio texto descarta la falta de voluntad política, porque dice que varios países sí invirtieron presupuesto.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select 'b423b103-e37f-4373-a3f6-7b10362662bf', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'economia-y-sociedad'),
  (select id from public.lotes where codigo = '2026-B'),
  '533eccc5-9e7b-4da1-9545-d0b093fd0a78', 'Economía y sociedad',
  'Aplicar en otra ciudad la iniciativa descrita requeriría',
  array['la asistencia del Estado y sus funcionarios para satisfacer las demandas de servicios de salud.', 'la participación solidaria y organizada de la comunidad en proyectos autónomos.', 'la inversión económica de la empresa privada para apoyar proyectos comunitarios.', 'la donación, por parte de hospitales y clínicas, de los equipos médicos necesarios.'],
  'Si el texto aclara de dónde NO viene el apoyo, ahí te está diciendo cuál es el verdadero motor de la iniciativa.', 'publicada', 'modelo', '5b74d487a63a5c4d306022eb9cf47177';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('b423b103-e37f-4373-a3f6-7b10362662bf', 1, 'La Central la crearon los propios vecinos: estudiaron enfermería, manejan las ambulancias y se financian con rifas y fiestas. El texto subraya que no recibe ayuda del Estado ni de privados. Replicarla exige entonces esa misma organización comunitaria, no el apoyo que la iniciativa justamente no tiene.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select '2356c286-71af-48ea-b51e-900b4d79c984', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'perspectivas-y-fuentes'),
  (select id from public.lotes where codigo = '2026-B'),
  '2adb8b95-1f5a-4e88-b5bb-2e481ab31155', 'Interpretación de perspectivas',
  'Por las posiciones políticas expresadas en este discurso, puede afirmarse que fue probablemente pronunciado por un líder con ideas políticas',
  array['de izquierda.', 'de derecha.', 'afines al liberalismo.', 'afines al proteccionismo.'],
  'Mira qué defiende y a quién ataca. El par «religión, familia y propiedad» contra «marxismo» ubica el discurso de inmediato.', 'publicada', 'modelo', 'f548566fe4a51bd04a7f9287340a1dec';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('2356c286-71af-48ea-b51e-900b4d79c984', 1, 'Quien habla ataca al anarquismo, al marxismo y al bolchevismo, y defiende la religión, la familia y la propiedad: esos tres valores, puestos en ese orden y frente a esos enemigos, son la bandera clásica de la derecha del siglo XX. La izquierda no combatiría al marxismo, y el proteccionismo es una política económica que aquí ni se menciona.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select 'e8916332-988d-4980-b6f9-729a3e8a3d48', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'perspectivas-y-fuentes'),
  (select id from public.lotes where codigo = '2026-B'),
  '41828da6-1fd1-4205-b65c-169af2f1e6b3', 'Interpretación de perspectivas',
  'De acuerdo con el texto anterior, Luther King luchó por',
  array['el respeto que inspiran las diferencias raciales y culturales.', 'la discriminación racial en lugares públicos.', 'la igualdad de los derechos civiles entre negros y blancos.', 'la defensa de la religión protestante.'],
  'Cuidado con la opción que repite una palabra del tema pero invierte el sentido: nadie lucha «por» la discriminación.', 'publicada', 'modelo', '89e557ad01a7a423dcffce1381641d4c';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('e8916332-988d-4980-b6f9-729a3e8a3d48', 2, 'El sueño que describe es el de personas de distinto color y credo tomándose de las manos y siendo por fin libres: lo que persigue es que todos valgan lo mismo. Luchar «por la discriminación» diría lo contrario de lo que pide, y aunque nombra a católicos y protestantes, no defiende a una religión sobre otra: las pone en pie de igualdad.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select '2e259036-7922-498a-a34e-d8476ea91c58', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'perspectivas-y-fuentes'),
  (select id from public.lotes where codigo = '2026-B'),
  '10f4fce5-b643-4db0-a715-2ee4cd54f0b5', 'Interpretación de perspectivas',
  'El anterior fragmento hace alusión a',
  array['los movimientos laborales del siglo XX.', 'el acceso de las mujeres a los cargos públicos.', 'la obtención del derecho al voto por las mujeres.', 'los logros de las mujeres durante la segunda mitad del siglo XX.'],
  'Si el texto enumera varios cambios distintos, la respuesta tiene que ser la más amplia, no una sola de las conquistas.', 'publicada', 'modelo', '3ff6a398c873e89344e39da64d302315';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('2e259036-7922-498a-a34e-d8476ea91c58', 3, 'El fragmento enumera varias conquistas a la vez: entrar a la universidad, controlar la natalidad, trabajar fuera de casa y descubrir la autonomía. Ninguna de las tres primeras opciones cubre ese conjunto; solo la que habla de los logros de las mujeres en ese periodo los abarca todos. El voto y los cargos públicos ni siquiera se mencionan.');

insert into public.preguntas (id, materia, tema_id, lote_id, contexto_id, comp, enunciado, opciones, tip, estado, clave_origen, hash_norm)
select '2c109bd7-71b2-4b0c-8ffd-9008476e223b', 'soc',
  (select id from public.temas where materia = 'soc' and codigo = 'perspectivas-y-fuentes'),
  (select id from public.lotes where codigo = '2026-B'),
  'ddadfef6-c2bc-47b6-8944-f7be96f70f23', 'Interpretación de perspectivas',
  '¿Qué argumento explica el cambio de posición del político frente a los medios de comunicación privados en los dos discursos citados?',
  array['En su condición de candidato a la presidencia, desconocía el poder y la influencia de los medios de comunicación privados sobre la ciudadanía. Siendo presidente, decidió darles un mayor impulso a los medios nacionales.', 'En su condición de candidato a la presidencia, no estaba interesado en perder el apoyo electoral de los medios de comunicación privados. Siendo presidente, buscó legitimar su proyecto político censurando a quienes se le opusieran.', 'En su condición de candidato a la presidencia, desconocía que los medios de comunicación privados también pueden estar al servicio de los valores nacionales. Siendo presidente, estaba interesado en incidir en los contenidos que estos producían.', 'En su condición de candidato a la presidencia, tenía como proyecto político sustituir progresivamente los medios de comunicación estatales por medios de comunicación privados. Siendo presidente, reconoció la importancia social de los medios estatales y decidió clausurar la competencia.'],
  'Cuando alguien cambia de posición, pregúntate qué necesitaba en cada momento. El interés suele explicar más que las ideas.', 'publicada', 'modelo', 'e172fbb7d453aac61e89bdd328ec433d';
insert into public.preguntas_clave (pregunta_id, correcta, explicacion) values ('2c109bd7-71b2-4b0c-8ffd-9008476e223b', 1, 'De candidato necesitaba a los medios privados y por eso los halagaba; ya de presidente, y después de un golpe fallido, cierra un canal acusándolo de golpismo. El cambio se explica porque en cada momento le convenía algo distinto: primero el apoyo para ganar, después el control para sostenerse. Las otras tres le atribuyen desconocimiento o un cambio de convicción que los discursos no muestran.');

insert into public.cuestionarios (id, materia, slug, seccion, titulo, tipo, orden, lote_id, publicado)
select 'aaf5380a-8b38-4429-bbb6-8e1851b0fe26', 'soc', 'soc-48', 'Constitución y derechos', 'Ambiente, género y derechos', 'Situación', 48,
  (select id from public.lotes where codigo = '2026-B'), true;
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('aaf5380a-8b38-4429-bbb6-8e1851b0fe26', 'e823bbc9-dad1-4703-aec1-d8304aa987e6', 1);
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('aaf5380a-8b38-4429-bbb6-8e1851b0fe26', 'faa427e8-f059-415f-8e0f-7fd348624cc5', 2);
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('aaf5380a-8b38-4429-bbb6-8e1851b0fe26', '0212c4ba-88ef-4d3d-9b2b-84b0a0c293f8', 3);

insert into public.cuestionarios (id, materia, slug, seccion, titulo, tipo, orden, lote_id, publicado)
select 'fd360b76-49eb-45ac-8622-145f61ce538f', 'soc', 'soc-49', 'Constitución y derechos', 'Universalidad y territorio', 'Situación', 49,
  (select id from public.lotes where codigo = '2026-B'), true;
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('fd360b76-49eb-45ac-8622-145f61ce538f', 'f80a3d69-0e27-43f5-8a97-412658c3988c', 1);
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('fd360b76-49eb-45ac-8622-145f61ce538f', '94cd26b3-ee9b-4f57-9a48-7e535ff97979', 2);
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('fd360b76-49eb-45ac-8622-145f61ce538f', '085d457d-48f9-4c21-8bc0-ca8e46e2d3ea', 3);

insert into public.cuestionarios (id, materia, slug, seccion, titulo, tipo, orden, lote_id, publicado)
select '98393912-1116-44a8-8ce4-9df823ae55a2', 'soc', 'soc-50', 'Economía y sociedad', 'Salud, hábitos y comunidad', 'Situación', 50,
  (select id from public.lotes where codigo = '2026-B'), true;
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('98393912-1116-44a8-8ce4-9df823ae55a2', '9f190c9f-6401-4e92-8836-8afca625ef91', 1);
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('98393912-1116-44a8-8ce4-9df823ae55a2', '964ad246-01c2-442e-94ae-ae070bce83b5', 2);
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('98393912-1116-44a8-8ce4-9df823ae55a2', 'b423b103-e37f-4373-a3f6-7b10362662bf', 3);

insert into public.cuestionarios (id, materia, slug, seccion, titulo, tipo, orden, lote_id, publicado)
select 'c03b1391-fe09-4c47-b651-21d1718d5496', 'soc', 'soc-51', 'Interpretación de perspectivas', 'Discursos e ideología', 'Situación', 51,
  (select id from public.lotes where codigo = '2026-B'), true;
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('c03b1391-fe09-4c47-b651-21d1718d5496', '2356c286-71af-48ea-b51e-900b4d79c984', 1);
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('c03b1391-fe09-4c47-b651-21d1718d5496', 'e8916332-988d-4980-b6f9-729a3e8a3d48', 2);
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('c03b1391-fe09-4c47-b651-21d1718d5496', '2e259036-7922-498a-a34e-d8476ea91c58', 3);
insert into public.cuestionario_preguntas (cuestionario_id, pregunta_id, orden) values ('c03b1391-fe09-4c47-b651-21d1718d5496', '2c109bd7-71b2-4b0c-8ffd-9008476e223b', 4);

